name: Client build
on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [develop]
    paths:
      - '.github/workflows/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'ios/**'
      - 'android/**'
jobs:
  buildandroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
      - run: echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
        # working-directory: ./
      - run: flutter build appbundle
      - run: flutter test
      - run: flutter analyze .
        # working-directory: ./lib